services:
  - type: web
    name: insa-helpdesk-api
    runtime: docker
    plan: free
    dockerfilePath: ./helpdesk-backend/Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: insa-helpdesk-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: insa-helpdesk-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: insa-helpdesk-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: insa-helpdesk-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: insa-helpdesk-db
          property: password
      - key: JWT_SECRET
        value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - key: FRONTEND_BASE_URL
        value: http://localhost:3000
      - key: MAIL_HOST
        value: sandbox.smtp.mailtrap.io
      - key: MAIL_PORT
        value: "2525"
      - key: MAIL_USERNAME
        value: dev
      - key: MAIL_PASSWORD
        value: dev
      - key: MAIL_FROM
        value: noreply@insa-helpdesk.local
      - key: JAVA_OPTS
        value: "-Xmx400m -Xms256m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

databases:
  - name: insa-helpdesk-db
    plan: free
    databaseName: insa_helpdesk
    ipAllowList: []
