services:
  - type: web
    name: insa-helpdesk-api
    runtime: docker
    plan: free
    dockerfilePath: ./helpdesk-backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: insa-helpdesk-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: insa-helpdesk-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: insa-helpdesk-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: insa-helpdesk-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: insa-helpdesk-db
          property: password
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_BASE_URL
        sync: false
      - key: MAIL_HOST
        value: sandbox.smtp.mailtrap.io
      - key: MAIL_PORT
        value: "2525"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        value: noreply@insa-helpdesk.local

databases:
  - name: insa-helpdesk-db
    plan: free
    databaseName: insa_helpdesk
    ipAllowList: []
