-- Reset all non-admin users to password: Helpdesk@1
-- Hash generated by the running backend's BCryptPasswordEncoder
UPDATE users
SET password_hash = '$2a$10$iYObk.yHxU/CtRC/1Tjwdu.LK0EqdjgCYkbtB/9uexnZsqvDZG8/G'
WHERE username != 'admin';

-- Clean up temp user
DELETE FROM users WHERE username = '_tmp_hash_user';

-- Verify
SELECT username, email, active,
       (SELECT name FROM roles WHERE id = role_id) as role
FROM users
ORDER BY id;
