-- ============================================================
-- INSA Helpdesk Demo Seed Script
-- Creates: 5 agents, 1 manager, 1 team, assigns tickets
-- ============================================================

-- ── 1. Departments ──────────────────────────────────────────
INSERT INTO departments (name) SELECT 'IT & Infrastructure' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE name = 'IT & Infrastructure');
INSERT INTO departments (name) SELECT 'Network Operations'  WHERE NOT EXISTS (SELECT 1 FROM departments WHERE name = 'Network Operations');
INSERT INTO departments (name) SELECT 'Human Resources'     WHERE NOT EXISTS (SELECT 1 FROM departments WHERE name = 'Human Resources');
INSERT INTO departments (name) SELECT 'Finance & Procurement' WHERE NOT EXISTS (SELECT 1 FROM departments WHERE name = 'Finance & Procurement');
INSERT INTO departments (name) SELECT 'Cyber Operations'    WHERE NOT EXISTS (SELECT 1 FROM departments WHERE name = 'Cyber Operations');

-- ── 2. Seed 5 agents + 1 team manager ──────────────────────
-- Password for ALL agents: Agent@1234
-- BCrypt hash of "Agent@1234" generated by the running backend
DO $$
DECLARE
  agent_role_id    BIGINT;
  manager_role_id  BIGINT;
  it_dept_id       BIGINT;
  noc_dept_id      BIGINT;
BEGIN
  SELECT id INTO agent_role_id   FROM roles WHERE name = 'HELPDESK_AGENT';
  SELECT id INTO manager_role_id FROM roles WHERE name = 'HELPDESK_MANAGER';
  SELECT id INTO it_dept_id      FROM departments WHERE name = 'IT & Infrastructure';
  SELECT id INTO noc_dept_id     FROM departments WHERE name = 'Network Operations';

  -- Agent 1: Network specialist
  IF NOT EXISTS (SELECT 1 FROM users WHERE username = 'abebe.bikila') THEN
    INSERT INTO users (username, email, password_hash, role_id, department_id, location, phone, active, auth_source)
    VALUES ('abebe.bikila', 'abebe.bikila@insa.gov.et',
            '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
            agent_role_id, noc_dept_id, 'Building A, Floor 2', '+251 91 123 0001', true, 'LOCAL');
    INSERT INTO user_expertise (user_id, expertise)
    SELECT id, e FROM users CROSS JOIN unnest(ARRAY['Network & VPN','Internet Connectivity']) e
    WHERE username = 'abebe.bikila';
  END IF;

  -- Agent 2: Software/ERP
  IF NOT EXISTS (SELECT 1 FROM users WHERE username = 'tigist.alemu') THEN
    INSERT INTO users (username, email, password_hash, role_id, department_id, location, phone, active, auth_source)
    VALUES ('tigist.alemu', 'tigist.alemu@insa.gov.et',
            '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
            agent_role_id, it_dept_id, 'Building B, Floor 1', '+251 91 123 0002', true, 'LOCAL');
    INSERT INTO user_expertise (user_id, expertise)
    SELECT id, e FROM users CROSS JOIN unnest(ARRAY['Software','ERP System','Microsoft Office']) e
    WHERE username = 'tigist.alemu';
  END IF;

  -- Agent 3: Hardware
  IF NOT EXISTS (SELECT 1 FROM users WHERE username = 'dawit.isaac') THEN
    INSERT INTO users (username, email, password_hash, role_id, department_id, location, phone, active, auth_source)
    VALUES ('dawit.isaac', 'dawit.isaac@insa.gov.et',
            '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
            agent_role_id, it_dept_id, 'Building A, Floor 3', '+251 91 123 0003', true, 'LOCAL');
    INSERT INTO user_expertise (user_id, expertise)
    SELECT id, e FROM users CROSS JOIN unnest(ARRAY['Hardware','Laptop/Desktop','Printer Setup']) e
    WHERE username = 'dawit.isaac';
  END IF;

  -- Agent 4: Access & Security
  IF NOT EXISTS (SELECT 1 FROM users WHERE username = 'sara.hailu') THEN
    INSERT INTO users (username, email, password_hash, role_id, department_id, location, phone, active, auth_source)
    VALUES ('sara.hailu', 'sara.hailu@insa.gov.et',
            '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
            agent_role_id, it_dept_id, 'Building C, Floor 1', '+251 91 123 0004', true, 'LOCAL');
    INSERT INTO user_expertise (user_id, expertise)
    SELECT id, e FROM users CROSS JOIN unnest(ARRAY['Access & Authentication','Password Reset','Account Locked']) e
    WHERE username = 'sara.hailu';
  END IF;

  -- Agent 5: General Tier-1
  IF NOT EXISTS (SELECT 1 FROM users WHERE username = 'yonas.tadesse') THEN
    INSERT INTO users (username, email, password_hash, role_id, department_id, location, phone, active, auth_source)
    VALUES ('yonas.tadesse', 'yonas.tadesse@insa.gov.et',
            '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
            agent_role_id, it_dept_id, 'Building B, Floor 2', '+251 91 123 0005', true, 'LOCAL');
    INSERT INTO user_expertise (user_id, expertise)
    SELECT id, e FROM users CROSS JOIN unnest(ARRAY['General Support','Communication Tools','Email Issues']) e
    WHERE username = 'yonas.tadesse';
  END IF;

  -- Manager: Helpdesk Manager
  IF NOT EXISTS (SELECT 1 FROM users WHERE username = 'selam.bekele') THEN
    INSERT INTO users (username, email, password_hash, role_id, department_id, location, phone, active, auth_source)
    VALUES ('selam.bekele', 'selam.bekele@insa.gov.et',
            '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
            manager_role_id, it_dept_id, 'Building A, Floor 1', '+251 91 123 0006', true, 'LOCAL');
  END IF;
END $$;

-- ── 3. Create the IT Support Team ───────────────────────────
INSERT INTO teams (name, description, is_default)
SELECT 'IT Support Team Alpha', 'Primary helpdesk team handling all IT support requests across INSA', true
WHERE NOT EXISTS (SELECT 1 FROM teams WHERE name = 'IT Support Team Alpha');

-- ── 4. Add all 5 agents to the team ─────────────────────────
INSERT INTO team_members (team_id, user_id)
SELECT t.id, u.id FROM teams t, users u
WHERE t.name = 'IT Support Team Alpha'
  AND u.username IN ('abebe.bikila','tigist.alemu','dawit.isaac','sara.hailu','yonas.tadesse')
  AND NOT EXISTS (SELECT 1 FROM team_members tm WHERE tm.team_id = t.id AND tm.user_id = u.id);

-- ── 5. Add routing rules to the team ────────────────────────
INSERT INTO team_routing_rules (team_id, category)
SELECT t.id, c FROM teams t
CROSS JOIN unnest(ARRAY[
  'Network & VPN','Hardware','Software','Access & Authentication',
  'General Support','ERP System','Email Issues','Internet Connectivity',
  'Printer Setup','Account Locked'
]) c
WHERE t.name = 'IT Support Team Alpha'
  AND NOT EXISTS (SELECT 1 FROM team_routing_rules tr WHERE tr.team_id = t.id AND tr.category = c);

-- ── 6. Seed demo end-users to submit tickets ─────────────────
DO $$
DECLARE end_user_role_id BIGINT;
BEGIN
  SELECT id INTO end_user_role_id FROM roles WHERE name = 'END_USER';

  IF NOT EXISTS (SELECT 1 FROM users WHERE username = 'bethlehem.t') THEN
    INSERT INTO users (username, email, password_hash, role_id, active, auth_source, location)
    VALUES ('bethlehem.t', 'bethlehem.t@insa.gov.et',
            '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
            end_user_role_id, true, 'LOCAL', 'Building B, Room 204');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM users WHERE username = 'kebede.m') THEN
    INSERT INTO users (username, email, password_hash, role_id, active, auth_source, location)
    VALUES ('kebede.m', 'kebede.m@insa.gov.et',
            '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
            end_user_role_id, true, 'LOCAL', 'Building C, Room 101');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM users WHERE username = 'meron.g') THEN
    INSERT INTO users (username, email, password_hash, role_id, active, auth_source, location)
    VALUES ('meron.g', 'meron.g@insa.gov.et',
            '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',
            end_user_role_id, true, 'LOCAL', 'Building A, Room 302');
  END IF;
END $$;

-- ── 7. Create tickets with DIFFERENT loads per agent ─────────
-- abebe.bikila   → 5 open tickets (most loaded)
-- tigist.alemu   → 3 open tickets
-- dawit.isaac    → 2 open tickets
-- sara.hailu     → 1 open ticket
-- yonas.tadesse  → 0 open tickets (available — will get next auto-assigned)

DO $$
DECLARE
  abebe_id   BIGINT; tigist_id  BIGINT; dawit_id   BIGINT;
  sara_id    BIGINT; yonas_id   BIGINT;
  reporter1  BIGINT; reporter2  BIGINT; reporter3  BIGINT;
  tid        BIGINT;
BEGIN
  SELECT id INTO abebe_id   FROM users WHERE username = 'abebe.bikila';
  SELECT id INTO tigist_id  FROM users WHERE username = 'tigist.alemu';
  SELECT id INTO dawit_id   FROM users WHERE username = 'dawit.isaac';
  SELECT id INTO sara_id    FROM users WHERE username = 'sara.hailu';
  SELECT id INTO yonas_id   FROM users WHERE username = 'yonas.tadesse';
  SELECT id INTO reporter1  FROM users WHERE username = 'bethlehem.t';
  SELECT id INTO reporter2  FROM users WHERE username = 'kebede.m';
  SELECT id INTO reporter3  FROM users WHERE username = 'meron.g';

  -- ── abebe.bikila: 5 tickets ──────────────────────────────
  IF (SELECT COUNT(*) FROM tickets WHERE assignee_id = abebe_id AND status = 'OPEN') < 5 THEN
    INSERT INTO tickets (ticket_number, title, description, status, priority, category, department, reporter_id, assignee_id, created_at, updated_at)
    VALUES
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+1 FROM tickets)::text,5,'0')),
     'VPN drops after 10 minutes of idle', 'Cisco AnyConnect disconnects exactly after 10 min idle. Affects all remote staff.', 'OPEN', 'HIGH', 'Network & VPN', 'Finance & Procurement', reporter1, abebe_id, NOW()-INTERVAL '2 days', NOW()-INTERVAL '1 hour'),
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+2 FROM tickets)::text,5,'0')),
     'Unable to access internal file share', 'Cannot reach \\fileserver\shared from Building B.', 'IN_PROGRESS', 'MEDIUM', 'Network & VPN', 'HR', reporter2, abebe_id, NOW()-INTERVAL '1 day', NOW()-INTERVAL '30 minutes'),
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+3 FROM tickets)::text,5,'0')),
     'WiFi dropping on Floor 3', 'Intermittent WiFi disconnects every 15 minutes on Floor 3.', 'OPEN', 'HIGH', 'Internet Connectivity', 'Operations', reporter3, abebe_id, NOW()-INTERVAL '3 days', NOW()-INTERVAL '2 hours'),
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+4 FROM tickets)::text,5,'0')),
     'Cannot connect to VPN from home', 'Remote staff unable to connect since password change.', 'OPEN', 'CRITICAL', 'Network & VPN', 'Cyber Operations', reporter1, abebe_id, NOW()-INTERVAL '4 hours', NOW()-INTERVAL '1 hour'),
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+5 FROM tickets)::text,5,'0')),
     'Slow internet on wired connection', 'Download speed under 1Mbps on LAN port Room 204.', 'OPEN', 'MEDIUM', 'Internet Connectivity', 'Finance & Procurement', reporter2, abebe_id, NOW()-INTERVAL '5 hours', NOW()-INTERVAL '2 hours');
  END IF;

  -- ── tigist.alemu: 3 tickets ──────────────────────────────
  IF (SELECT COUNT(*) FROM tickets WHERE assignee_id = tigist_id AND status IN ('OPEN','IN_PROGRESS')) < 3 THEN
    INSERT INTO tickets (ticket_number, title, description, status, priority, category, department, reporter_id, assignee_id, created_at, updated_at)
    VALUES
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+6 FROM tickets)::text,5,'0')),
     'ERP login error after password change', 'Getting "Invalid credentials" on ERP after AD password reset.', 'OPEN', 'HIGH', 'ERP System', 'Finance & Procurement', reporter2, tigist_id, NOW()-INTERVAL '6 hours', NOW()-INTERVAL '1 hour'),
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+7 FROM tickets)::text,5,'0')),
     'Microsoft Office activation expired', 'Office suite showing "Unlicensed Product" on 3 workstations.', 'IN_PROGRESS', 'MEDIUM', 'Software', 'HR', reporter3, tigist_id, NOW()-INTERVAL '1 day', NOW()-INTERVAL '3 hours'),
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+8 FROM tickets)::text,5,'0')),
     'ERP reports page not loading', 'Reports module throws 500 error. Affects all Finance users.', 'OPEN', 'HIGH', 'ERP System', 'Finance & Procurement', reporter1, tigist_id, NOW()-INTERVAL '8 hours', NOW()-INTERVAL '2 hours');
  END IF;

  -- ── dawit.isaac: 2 tickets ───────────────────────────────
  IF (SELECT COUNT(*) FROM tickets WHERE assignee_id = dawit_id AND status IN ('OPEN','IN_PROGRESS')) < 2 THEN
    INSERT INTO tickets (ticket_number, title, description, status, priority, category, department, reporter_id, assignee_id, created_at, updated_at)
    VALUES
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+9 FROM tickets)::text,5,'0')),
     'Laptop screen flickering', 'Dell Latitude screen flickers on battery. Asset: INSA-LT-042.', 'IN_PROGRESS', 'MEDIUM', 'Hardware', 'Operations', reporter3, dawit_id, NOW()-INTERVAL '2 days', NOW()-INTERVAL '4 hours'),
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+10 FROM tickets)::text,5,'0')),
     'Printer on Floor 2 offline', 'Canon IR2525 showing offline. Queue has 14 pending jobs.', 'OPEN', 'HIGH', 'Printer Setup', 'HR', reporter1, dawit_id, NOW()-INTERVAL '3 hours', NOW()-INTERVAL '1 hour');
  END IF;

  -- ── sara.hailu: 1 ticket ─────────────────────────────────
  IF (SELECT COUNT(*) FROM tickets WHERE assignee_id = sara_id AND status IN ('OPEN','IN_PROGRESS')) < 1 THEN
    INSERT INTO tickets (ticket_number, title, description, status, priority, category, department, reporter_id, assignee_id, created_at, updated_at)
    VALUES
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+11 FROM tickets)::text,5,'0')),
     'Account locked after 5 failed attempts', 'User locked out. Needs immediate unlock and MFA review.', 'OPEN', 'MEDIUM', 'Account Locked', 'Legal & Policy', reporter2, sara_id, NOW()-INTERVAL '1 hour', NOW()-INTERVAL '30 minutes');
  END IF;

  -- ── yonas.tadesse: 0 open (has 1 resolved to show history) ─
  IF NOT EXISTS (SELECT 1 FROM tickets WHERE assignee_id = yonas_id) THEN
    INSERT INTO tickets (ticket_number, title, description, status, priority, category, department, reporter_id, assignee_id, created_at, updated_at)
    VALUES
    (CONCAT('TK-', LPAD((SELECT COALESCE(MAX(id),0)+12 FROM tickets)::text,5,'0')),
     'Outlook not syncing emails', 'Inbox not updating since yesterday. Issue now resolved.', 'RESOLVED', 'LOW', 'Email Issues', 'HR', reporter3, yonas_id, NOW()-INTERVAL '1 day', NOW()-INTERVAL '2 hours');
  END IF;
END $$;

-- ── 8. Verify ────────────────────────────────────────────────
SELECT
  u.username,
  r.name as role,
  d.name as department,
  COUNT(t.id) FILTER (WHERE t.status IN ('OPEN','IN_PROGRESS')) as open_tickets,
  COUNT(t.id) FILTER (WHERE t.status = 'RESOLVED') as resolved_tickets
FROM users u
JOIN roles r ON r.id = u.role_id
LEFT JOIN departments d ON d.id = u.department_id
LEFT JOIN tickets t ON t.assignee_id = u.id
WHERE u.username IN ('abebe.bikila','tigist.alemu','dawit.isaac','sara.hailu','yonas.tadesse','selam.bekele')
GROUP BY u.username, r.name, d.name
ORDER BY open_tickets DESC;
